# las_vegas Track Configuration
pit_entry = 0.9688
pit_lane_displacement = 0.1015

# DRS Configuration
[drs]
delta_for_drs_activation = 1.0  # Standard value in F1, but can be overridden by RaceConfiguration
drs_activation_lap = 3          # Standard value in F1, but can be overridden by RaceConfiguration

# DRS Zones
[[drs.drs_zones]]
drs_boost = 1.0000 # default value for tracks 
detection_point = 0.0785
activation_point_start = 0.1308
activation_point_end = 0.2453

[[drs.drs_zones]]
drs_boost = 1.0000 # default value for tracks 
detection_point = 0.6434
activation_point_start = 0.6998
activation_point_end = 0.8339

