# mexico_city Track Configuration
pit_entry = 0.9514
pit_lane_displacement = 0.1856

# DRS Configuration
[drs]
delta_for_drs_activation = 1.0  # Standard value in F1, but can be overridden by RaceConfiguration
drs_activation_lap = 3          # Standard value in F1, but can be overridden by RaceConfiguration

# DRS Zones
[[drs.drs_zones]]
drs_boost = 1.0000 # default value for tracks 
detection_point = 0.9433
activation_point_start = 0.0465
activation_point_end = 0.2788

[[drs.drs_zones]]
drs_boost = 1.0000 # default value for tracks 
detection_point = 0.9433
activation_point_start = 0.3601
activation_point_end = 0.4902

[[drs.drs_zones]]
drs_boost = 1.0000 # default value for tracks 
detection_point = 0.6993
activation_point_start = 0.7691
activation_point_end = 0.8736

