# singapore Track Configuration
pit_entry = 0.9397
pit_lane_displacement = 0.1628

# DRS Configuration
[drs]
delta_for_drs_activation = 1.0  # Standard value in F1, but can be overridden by RaceConfiguration
drs_activation_lap = 3          # Standard value in F1, but can be overridden by RaceConfiguration

# DRS Zones
[[drs.drs_zones]]
drs_boost = 1.0000 # default value for tracks 
detection_point = 0.9113
activation_point_start = 0.9752
activation_point_end = 0.0802

[[drs.drs_zones]]
drs_boost = 1.0000 # default value for tracks 
detection_point = 0.1593
activation_point_start = 0.2141
activation_point_end = 0.3481

[[drs.drs_zones]]
drs_boost = 1.0000 # default value for tracks 
detection_point = 0.5927
activation_point_start = 0.6444
activation_point_end = 0.7144

[[drs.drs_zones]]
drs_boost = 1.0000 # default value for tracks 
detection_point = 0.5927
activation_point_start = 0.7591
activation_point_end = 0.8667

