# spielberg Track Configuration
pit_entry = 0.8957
pit_lane_displacement = 0.2291

# DRS Configuration
[drs]
delta_for_drs_activation = 1.0  # Standard value in F1, but can be overridden by RaceConfiguration
drs_activation_lap = 3          # Standard value in F1, but can be overridden by RaceConfiguration

# DRS Zones
[[drs.drs_zones]]
drs_boost = 1.0000 # default value for tracks 
detection_point = 0.8911
activation_point_start = 0.9374
activation_point_end = 0.0925

[[drs.drs_zones]]
drs_boost = 1.0000 # default value for tracks 
detection_point = 0.0832
activation_point_start = 0.1225
activation_point_end = 0.3098

