# zandvoort Track Configuration
pit_entry = 0.9075
pit_lane_displacement = 0.2017

# DRS Configuration
[drs]
delta_for_drs_activation = 1.0  # Standard value in F1, but can be overridden by RaceConfiguration
drs_activation_lap = 3          # Standard value in F1, but can be overridden by RaceConfiguration

# DRS Zones
[[drs.drs_zones]]
drs_boost = 1.0000 # default value for tracks 
detection_point = 0.7584
activation_point_start = 0.8476
activation_point_end = 0.0634

[[drs.drs_zones]]
drs_boost = 1.0000 # default value for tracks 
detection_point = 0.5753
activation_point_start = 0.6069
activation_point_end = 0.7161

